name: xdag
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.1+25

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_statusbarcolor_ns: ^0.6.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0
  local_auth: ^2.3.0
  chinese_font_library: ^1.0.1
  local_auth_android: ^1.0.47
  local_auth_darwin: ^1.4.3
  provider: ^6.0.5
  auto_size_text_field: ^2.2.1
  flutter_keyboard_visibility: ^5.4.0
  window_manager: ^0.3.2
  scan_qr:
    git:
      url: https://github.com/amazingCoding/flutter-scan-qr.git
  package_info_plus: ^3.0.3
  dio: ^5.0.3
  back_to_home:
    git:
      url: https://github.com/amazingCoding/flutter-back-to-phone-home.git
  easy_refresh: ^3.3.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  webview_flutter: ^4.2.0
  crypto: ^3.0.2
  fast_base58: ^0.2.1
  secp256k1: ^0.3.0
  url_launcher: ^6.1.10
  hex: ^0.2.0
  fixnum: ^1.1.0
  pointycastle: ^3.6.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  event_bus: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_timezone: ^4.1.0  
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3
  vision_gallery_saver: ^2.0.2
dependency_overrides:
   win32: ^5.5.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "images/1024.png"
    icon_size: 256
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo40.png
    - images/2.0x/logo40.png
    - images/3.0x/logo40.png

    - images/logo80.png
    - images/2.0x/logo80.png
    - images/3.0x/logo80.png
    
    - images/p1.png
    - images/2.0x/p1.png
    - images/3.0x/p1.png
    
    - images/p2.png
    - images/2.0x/p2.png
    - images/3.0x/p2.png
    
    - images/p3.png
    - images/2.0x/p3.png
    - images/3.0x/p3.png
    
    - images/start.png
    - images/2.0x/start.png
    - images/3.0x/start.png

    - images/lock.png
    - images/2.0x/lock.png
    - images/3.0x/lock.png

    - images/wallet.png
    - images/2.0x/wallet.png
    - images/3.0x/wallet.png
    - images/wallet1.png
    - images/2.0x/wallet1.png
    - images/3.0x/wallet1.png

    - images/set.png
    - images/2.0x/set.png
    - images/3.0x/set.png
    - images/set1.png
    - images/2.0x/set1.png
    - images/3.0x/set1.png

    - images/receive.png
    - images/2.0x/receive.png
    - images/3.0x/receive.png

    - images/send.png
    - images/2.0x/send.png
    - images/3.0x/send.png

    - images/security.png
    - images/2.0x/security.png
    - images/3.0x/security.png

    - images/aboutus.png
    - images/2.0x/aboutus.png
    - images/3.0x/aboutus.png

    - images/document.png
    - images/2.0x/document.png
    - images/3.0x/document.png

    - images/security_gray.png
    - images/2.0x/security_gray.png
    - images/3.0x/security_gray.png

    - images/security_main.png
    - images/2.0x/security_main.png
    - images/3.0x/security_main.png

    - images/telegram.png
    - images/2.0x/telegram.png
    - images/3.0x/telegram.png

    - images/twitter.png
    - images/2.0x/twitter.png
    - images/3.0x/twitter.png

    - images/discord.png
    - images/2.0x/discord.png
    - images/3.0x/discord.png

    - images/website.png
    - images/2.0x/website.png
    - images/3.0x/website.png

    - images/delete_red.png
    - images/2.0x/delete_red.png
    - images/3.0x/delete_red.png

    - images/switch.png
    - images/2.0x/switch.png
    - images/3.0x/switch.png

    - images/key.png
    - images/2.0x/key.png
    - images/3.0x/key.png

    - images/face_id.png
    - images/2.0x/face_id.png
    - images/3.0x/face_id.png

    - images/biometrics.png
    - images/2.0x/biometrics.png
    - images/3.0x/biometrics.png

    - images/snapshot.png
    - images/2.0x/snapshot.png
    - images/3.0x/snapshot.png

    - images/like.png
    - images/2.0x/like.png
    - images/3.0x/like.png

    - images/security_1.png
    - images/2.0x/security_1.png
    - images/3.0x/security_1.png

    - images/contacts.png
    - images/2.0x/contacts.png
    - images/3.0x/contacts.png

    - images/contacts1.png
    - images/2.0x/contacts1.png
    - images/3.0x/contacts1.png

    - images/logo_b_40.png
    - images/2.0x/logo_b_40.png
    - images/3.0x/logo_b_40.png

    - images/qr.png
    - images/2.0x/qr.png
    - images/3.0x/qr.png

    - images/logo.png
    - images/2.0x/logo.png
    - images/3.0x/logo.png

    - images/set_white.png
    - images/2.0x/set_white.png
    - images/3.0x/set_white.png

    - images/wallet_white.png
    - images/2.0x/wallet_white.png
    - images/3.0x/wallet_white.png

    - images/desktop_lang.png
    - images/2.0x/desktop_lang.png
    - images/3.0x/desktop_lang.png

    - images/desktop_network.png
    - images/2.0x/desktop_network.png
    - images/3.0x/desktop_network.png

    - images/desktop_legal.png
    - images/2.0x/desktop_legal.png
    - images/3.0x/desktop_legal.png

    - images/desktop_security.png
    - images/2.0x/desktop_security.png
    - images/3.0x/desktop_security.png

    - images/home.png
    - images/2.0x/home.png
    - images/3.0x/home.png

    - images/ref.png
    - images/2.0x/ref.png
    - images/3.0x/ref.png

    - images/lock_icon.png
    - images/2.0x/lock_icon.png
    - images/3.0x/lock_icon.png

    - images/contacts_white.png
    - images/2.0x/contacts_white.png
    - images/3.0x/contacts_white.png

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: roboto-mono/RobotoMono-Thin.ttf
          weight: 100
        - asset: roboto-mono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: roboto-mono/RobotoMono-Light.ttf
          weight: 300
        - asset: roboto-mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: roboto-mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: roboto-mono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: roboto-mono/RobotoMono-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
